#!/usr/bin/env bash

clear

# Testar se foi passado apenas um argumento...
[[ $# -ne 1 ]] && echo "Precisa de um argumento!" && exit 1

echo -e "Iniciando ordenação"
echo

tr -s '[:space:]' ' ' < $1 > arquivo1.txt
tr -s '[:space:]' '\n' < arquivo1.txt > arquivo2.txt

sort arquivo2.txt > arquivo3.txt

cat  "arquivo3.txt" | xargs > pronto.txt

rm arquivo1.txt arquivo2.txt arquivo3.txt

echo "Ordenação finalizada."
echo

