#!/usr/bin/env bash
#----------------------------------------------------------------------
# Script    : [remove.sh]
# Descrição :
# Versão    : 1.0
# Autor     : Fabio Junior Ribeiro
# Email     : rib3iro@live.com
# Github    : https://github.com/frib3iro
# Data      : 08/04/2022
# Licença   : GNU/GPL v3.0
#----------------------------------------------------------------------
# Uso       :
#----------------------------------------------------------------------
clear

# Testar se foi passado apenas um argumento...
[[ $# -ne 1 ]] && echo "Precisa do nome do arquivo!" && exit 1

echo "Removendo o ecesso de espaços com tr"
sleep 2s
tr -s ' ' ' ' < $1 > temp

echo
echo "Trocando espaços por quebra de linha com tr"
sleep 2s
tr ' ' '\n' < temp > $1

echo
echo "Organizando e removendo duplicados com sort"
sleep 2s
sort -u $1 > temp

echo
echo "Trocando quebra de linha por espaço com tr "
sleep 2s
tr '\n' ' ' < temp > $1

echo
echo "Procedimento finalizado!"
sleep 2s
rm temp
echo
cat $1
echo
echo
